namespace InventoryManagementSystem
{
    partial class MainForm
    {
        private System.ComponentModel.IContainer components = null;
        
        // Top Bar Components
        private Panel panelTopBar;
        private TextBox txtGlobalSearch;
        private Button btnAlerts;
        private Label lblOrganization;
        
        // Left Sidebar Components
        private Panel panelSidebar;
        private Button btnDashboard;
        private Button btnProducts;
        private Button btnStock;
        private Button btnOrders;
        private Button btnSuppliers;
        private Button btnReports;
        private Button btnCollapseSidebar;
        
        // Main Content Area
        private Panel panelMainContent;
        private Panel panelContentHeader;
        private Label lblPageTitle;
        private Label lblPageSubtitle;
        private Panel panelDataTable;
        private DataGridView dgvMainData;
        
        // Right Context Drawer
        private Panel panelContextDrawer;
        private Button btnCloseDrawer;
        private Label lblDrawerTitle;
        private Panel panelDrawerContent;
        
        // Dashboard specific components
        private Panel panelDashboard;
        private Label lblTotalProducts;
        private Label lblLowStockCount;
        private Label lblTotalValue;
        private Label lblTodaySales;
        private Label lblTotalProductsLabel;
        private Label lblLowStockLabel;
        private Label lblTotalValueLabel;
        private Label lblTodaySalesLabel;
        private DataGridView dgvLowStock;
        private DataGridView dgvRecentTransactions;
        private Label lblLowStockTitle;
        private Label lblRecentTransactionsTitle;

        private void InitializeComponent()
        {
            panelTopBar = new Panel();
            txtGlobalSearch = new TextBox();
            btnAlerts = new Button();
            lblOrganization = new Label();
            panelSidebar = new Panel();
            btnDashboard = new Button();
            btnProducts = new Button();
            btnStock = new Button();
            btnOrders = new Button();
            btnSuppliers = new Button();
            btnReports = new Button();
            btnCollapseSidebar = new Button();
            panelMainContent = new Panel();
            panelContentHeader = new Panel();
            lblPageTitle = new Label();
            lblPageSubtitle = new Label();
            panelDataTable = new Panel();
            dgvMainData = new DataGridView();
            panelContextDrawer = new Panel();
            btnCloseDrawer = new Button();
            lblDrawerTitle = new Label();
            panelDrawerContent = new Panel();
            panelDashboard = new Panel();
            lblTotalProducts = new Label();
            lblLowStockCount = new Label();
            lblTotalValue = new Label();
            lblTodaySales = new Label();
            lblTotalProductsLabel = new Label();
            lblLowStockLabel = new Label();
            lblTotalValueLabel = new Label();
            lblTodaySalesLabel = new Label();
            dgvLowStock = new DataGridView();
            dgvRecentTransactions = new DataGridView();
            lblLowStockTitle = new Label();
            lblRecentTransactionsTitle = new Label();
            panelTopBar.SuspendLayout();
            panelSidebar.SuspendLayout();
            panelMainContent.SuspendLayout();
            panelContentHeader.SuspendLayout();
            panelDataTable.SuspendLayout();
            panelContextDrawer.SuspendLayout();
            panelDrawerContent.SuspendLayout();
            panelDashboard.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvMainData).BeginInit();
            ((System.ComponentModel.ISupportInitialize)dgvLowStock).BeginInit();
            ((System.ComponentModel.ISupportInitialize)dgvRecentTransactions).BeginInit();
            SuspendLayout();
            // MainForm - Modern Enterprise Layout
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1920, 1080);
            Text = "Inventory Management System";
            StartPosition = FormStartPosition.CenterScreen;
            BackColor = Color.FromArgb(15, 23, 42);
            Font = new Font("Segoe UI", 9F);
            WindowState = FormWindowState.Maximized;
            MinimumSize = new Size(1400, 900);
            // Top Bar - Global Navigation
            panelTopBar.Controls.Add(txtGlobalSearch);
            panelTopBar.Controls.Add(btnAlerts);
            panelTopBar.Controls.Add(lblOrganization);
            panelTopBar.Dock = DockStyle.Top;
            panelTopBar.Height = 60;
            panelTopBar.BackColor = Color.FromArgb(30, 41, 59);
            panelTopBar.Padding = new Padding(20, 10, 20, 10);
            // Global Search
            txtGlobalSearch.Location = new Point(20, 15);
            txtGlobalSearch.Size = new Size(400, 30);
            txtGlobalSearch.Font = new Font("Segoe UI", 11F);
            txtGlobalSearch.BackColor = Color.FromArgb(51, 65, 85);
            txtGlobalSearch.ForeColor = Color.White;
            txtGlobalSearch.BorderStyle = BorderStyle.FixedSingle;
            txtGlobalSearch.PlaceholderText = "Search products, SKUs, orders...";
            // Alerts
            btnAlerts.Text = "⚠️ 3";
            btnAlerts.Location = new Point(1500, 15);
            btnAlerts.Size = new Size(60, 30);
            btnAlerts.BackColor = Color.FromArgb(239, 68, 68);
            btnAlerts.ForeColor = Color.White;
            btnAlerts.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            btnAlerts.FlatStyle = FlatStyle.Flat;
            btnAlerts.FlatAppearance.BorderSize = 0;
            btnAlerts.Cursor = Cursors.Hand;
            btnAlerts.Click += btnAlerts_Click;
            // Organization
            lblOrganization.Text = "🏢 Acme Corp";
            lblOrganization.Location = new Point(1620, 15);
            lblOrganization.Size = new Size(120, 30);
            lblOrganization.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblOrganization.ForeColor = Color.White;
            lblOrganization.TextAlign = ContentAlignment.MiddleLeft;
            // Left Sidebar - Navigation Menu
            panelSidebar.Controls.Add(btnDashboard);
            panelSidebar.Controls.Add(btnProducts);
            panelSidebar.Controls.Add(btnStock);
            panelSidebar.Controls.Add(btnOrders);
            panelSidebar.Controls.Add(btnSuppliers);
            panelSidebar.Controls.Add(btnReports);
            panelSidebar.Controls.Add(btnCollapseSidebar);
            panelSidebar.Dock = DockStyle.Left;
            panelSidebar.Width = 250;
            panelSidebar.BackColor = Color.FromArgb(30, 41, 59);
            panelSidebar.Padding = new Padding(10);
            // Navigation Buttons
            btnDashboard.Text = "📊 Dashboard";
            btnDashboard.Location = new Point(10, 20);
            btnDashboard.Size = new Size(230, 45);
            btnDashboard.BackColor = Color.FromArgb(59, 130, 246);
            btnDashboard.ForeColor = Color.White;
            btnDashboard.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            btnDashboard.FlatStyle = FlatStyle.Flat;
            btnDashboard.FlatAppearance.BorderSize = 0;
            btnDashboard.Cursor = Cursors.Hand;
            btnDashboard.TextAlign = ContentAlignment.MiddleLeft;
            btnDashboard.Click += btnDashboard_Click;
            btnProducts.Text = "📦 Products";
            btnProducts.Location = new Point(10, 75);
            btnProducts.Size = new Size(230, 45);
            btnProducts.BackColor = Color.FromArgb(51, 65, 85);
            btnProducts.ForeColor = Color.White;
            btnProducts.Font = new Font("Segoe UI", 11F);
            btnProducts.FlatStyle = FlatStyle.Flat;
            btnProducts.FlatAppearance.BorderSize = 0;
            btnProducts.Cursor = Cursors.Hand;
            btnProducts.TextAlign = ContentAlignment.MiddleLeft;
            btnProducts.Click += btnProducts_Click;
            btnStock.Text = "📊 Stock";
            btnStock.Location = new Point(10, 130);
            btnStock.Size = new Size(230, 45);
            btnStock.BackColor = Color.FromArgb(51, 65, 85);
            btnStock.ForeColor = Color.White;
            btnStock.Font = new Font("Segoe UI", 11F);
            btnStock.FlatStyle = FlatStyle.Flat;
            btnStock.FlatAppearance.BorderSize = 0;
            btnStock.Cursor = Cursors.Hand;
            btnStock.TextAlign = ContentAlignment.MiddleLeft;
            btnStock.Click += btnStock_Click;
            btnOrders.Text = "💰 Orders";
            btnOrders.Location = new Point(10, 185);
            btnOrders.Size = new Size(230, 45);
            btnOrders.BackColor = Color.FromArgb(51, 65, 85);
            btnOrders.ForeColor = Color.White;
            btnOrders.Font = new Font("Segoe UI", 11F);
            btnOrders.FlatStyle = FlatStyle.Flat;
            btnOrders.FlatAppearance.BorderSize = 0;
            btnOrders.Cursor = Cursors.Hand;
            btnOrders.TextAlign = ContentAlignment.MiddleLeft;
            btnOrders.Click += btnOrders_Click;
            btnSuppliers.Text = "🏭 Suppliers";
            btnSuppliers.Location = new Point(10, 240);
            btnSuppliers.Size = new Size(230, 45);
            btnSuppliers.BackColor = Color.FromArgb(51, 65, 85);
            btnSuppliers.ForeColor = Color.White;
            btnSuppliers.Font = new Font("Segoe UI", 11F);
            btnSuppliers.FlatStyle = FlatStyle.Flat;
            btnSuppliers.FlatAppearance.BorderSize = 0;
            btnSuppliers.Cursor = Cursors.Hand;
            btnSuppliers.TextAlign = ContentAlignment.MiddleLeft;
            btnSuppliers.Click += btnSuppliers_Click;
            btnReports.Text = "📈 Reports";
            btnReports.Location = new Point(10, 295);
            btnReports.Size = new Size(230, 45);
            btnReports.BackColor = Color.FromArgb(51, 65, 85);
            btnReports.ForeColor = Color.White;
            btnReports.Font = new Font("Segoe UI", 11F);
            btnReports.FlatStyle = FlatStyle.Flat;
            btnReports.FlatAppearance.BorderSize = 0;
            btnReports.Cursor = Cursors.Hand;
            btnReports.TextAlign = ContentAlignment.MiddleLeft;
            btnReports.Click += btnReports_Click;
            // Collapse Sidebar Button
            btnCollapseSidebar.Text = "◀";
            btnCollapseSidebar.Location = new Point(10, 500);
            btnCollapseSidebar.Size = new Size(40, 30);
            btnCollapseSidebar.BackColor = Color.FromArgb(107, 114, 128);
            btnCollapseSidebar.ForeColor = Color.White;
            btnCollapseSidebar.Font = new Font("Segoe UI", 10F);
            btnCollapseSidebar.FlatStyle = FlatStyle.Flat;
            btnCollapseSidebar.FlatAppearance.BorderSize = 0;
            btnCollapseSidebar.Cursor = Cursors.Hand;
            btnCollapseSidebar.Click += btnCollapseSidebar_Click;
            // Main Content Area
            panelMainContent.Controls.Add(panelContentHeader);
            panelMainContent.Controls.Add(panelDataTable);
            panelMainContent.Dock = DockStyle.Fill;
            panelMainContent.BackColor = Color.FromArgb(15, 23, 42);
            panelMainContent.Padding = new Padding(20);
            // Content Header
            panelContentHeader.Controls.Add(lblPageTitle);
            panelContentHeader.Controls.Add(lblPageSubtitle);
            panelContentHeader.Dock = DockStyle.Top;
            panelContentHeader.Height = 80;
            panelContentHeader.BackColor = Color.FromArgb(30, 41, 59);
            panelContentHeader.Padding = new Padding(20);
            lblPageTitle.Text = "📊 Dashboard";
            lblPageTitle.Location = new Point(20, 15);
            lblPageTitle.Size = new Size(400, 35);
            lblPageTitle.Font = new Font("Segoe UI", 20F, FontStyle.Bold);
            lblPageTitle.ForeColor = Color.White;
            lblPageSubtitle.Text = "Overview of your inventory and business metrics";
            lblPageSubtitle.Location = new Point(20, 50);
            lblPageSubtitle.Size = new Size(600, 25);
            lblPageSubtitle.Font = new Font("Segoe UI", 12F);
            lblPageSubtitle.ForeColor = Color.FromArgb(148, 163, 184);
            // Data Table Panel
            panelDataTable.Controls.Add(dgvMainData);
            panelDataTable.Dock = DockStyle.Fill;
            panelDataTable.BackColor = Color.FromArgb(30, 41, 59);
            panelDataTable.Padding = new Padding(20);
            // Main Data Grid
            dgvMainData.Dock = DockStyle.Fill;
            dgvMainData.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvMainData.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvMainData.BackgroundColor = Color.FromArgb(30, 41, 59);
            dgvMainData.BorderStyle = BorderStyle.None;
            dgvMainData.GridColor = Color.FromArgb(51, 65, 85);
            dgvMainData.Font = new Font("Segoe UI", 10F);
            dgvMainData.ForeColor = Color.White;
            dgvMainData.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(51, 65, 85);
            dgvMainData.ColumnHeadersDefaultCellStyle.ForeColor = Color.White;
            dgvMainData.ColumnHeadersDefaultCellStyle.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            dgvMainData.RowsDefaultCellStyle.BackColor = Color.FromArgb(30, 41, 59);
            dgvMainData.RowsDefaultCellStyle.ForeColor = Color.White;
            dgvMainData.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(51, 65, 85);
            dgvMainData.AlternatingRowsDefaultCellStyle.ForeColor = Color.White;
            dgvMainData.SelectionChanged += dgvMainData_SelectionChanged;
            // Right Context Drawer
            panelContextDrawer.Controls.Add(btnCloseDrawer);
            panelContextDrawer.Controls.Add(lblDrawerTitle);
            panelContextDrawer.Controls.Add(panelDrawerContent);
            panelContextDrawer.Dock = DockStyle.Right;
            panelContextDrawer.Width = 400;
            panelContextDrawer.BackColor = Color.FromArgb(51, 65, 85);
            panelContextDrawer.Visible = false;
            btnCloseDrawer.Text = "✕";
            btnCloseDrawer.Location = new Point(360, 10);
            btnCloseDrawer.Size = new Size(30, 30);
            btnCloseDrawer.BackColor = Color.FromArgb(239, 68, 68);
            btnCloseDrawer.ForeColor = Color.White;
            btnCloseDrawer.Font = new Font("Segoe UI", 10F);
            btnCloseDrawer.FlatStyle = FlatStyle.Flat;
            btnCloseDrawer.FlatAppearance.BorderSize = 0;
            btnCloseDrawer.Cursor = Cursors.Hand;
            btnCloseDrawer.Click += btnCloseDrawer_Click;
            lblDrawerTitle.Text = "Quick View";
            lblDrawerTitle.Location = new Point(20, 15);
            lblDrawerTitle.Size = new Size(200, 25);
            lblDrawerTitle.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            lblDrawerTitle.ForeColor = Color.White;
            panelDrawerContent.Location = new Point(20, 50);
            panelDrawerContent.Size = new Size(360, 600);
            panelDrawerContent.BackColor = Color.FromArgb(30, 41, 59);
            // Dashboard Panel (initially visible)
            panelDashboard.Controls.Add(lblTotalProductsLabel);
            panelDashboard.Controls.Add(lblTotalProducts);
            panelDashboard.Controls.Add(lblLowStockLabel);
            panelDashboard.Controls.Add(lblLowStockCount);
            panelDashboard.Controls.Add(lblTotalValueLabel);
            panelDashboard.Controls.Add(lblTotalValue);
            panelDashboard.Controls.Add(lblTodaySalesLabel);
            panelDashboard.Controls.Add(lblTodaySales);
            panelDashboard.Controls.Add(lblLowStockTitle);
            panelDashboard.Controls.Add(dgvLowStock);
            panelDashboard.Controls.Add(lblRecentTransactionsTitle);
            panelDashboard.Controls.Add(dgvRecentTransactions);
            panelDashboard.Dock = DockStyle.Fill;
            panelDashboard.BackColor = Color.FromArgb(15, 23, 42);
            panelDashboard.Padding = new Padding(20);
            // Dashboard Stats Cards
            lblTotalProductsLabel.Text = "📦 Total Products";
            lblTotalProductsLabel.Location = new Point(20, 20);
            lblTotalProductsLabel.Size = new Size(200, 30);
            lblTotalProductsLabel.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            lblTotalProductsLabel.ForeColor = Color.FromArgb(148, 163, 184);
            lblTotalProducts.Text = "0";
            lblTotalProducts.Location = new Point(20, 50);
            lblTotalProducts.Size = new Size(200, 50);
            lblTotalProducts.Font = new Font("Segoe UI", 28F, FontStyle.Bold);
            lblTotalProducts.ForeColor = Color.FromArgb(59, 130, 246);
            lblLowStockLabel.Text = "⚠️ Low Stock Items";
            lblLowStockLabel.Location = new Point(240, 20);
            lblLowStockLabel.Size = new Size(200, 30);
            lblLowStockLabel.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            lblLowStockLabel.ForeColor = Color.FromArgb(148, 163, 184);
            lblLowStockCount.Text = "0";
            lblLowStockCount.Location = new Point(240, 50);
            lblLowStockCount.Size = new Size(200, 50);
            lblLowStockCount.Font = new Font("Segoe UI", 28F, FontStyle.Bold);
            lblLowStockCount.ForeColor = Color.FromArgb(239, 68, 68);
            lblTotalValueLabel.Text = "💰 Total Inventory Value";
            lblTotalValueLabel.Location = new Point(460, 20);
            lblTotalValueLabel.Size = new Size(200, 30);
            lblTotalValueLabel.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            lblTotalValueLabel.ForeColor = Color.FromArgb(148, 163, 184);
            lblTotalValue.Text = "$0.00";
            lblTotalValue.Location = new Point(460, 50);
            lblTotalValue.Size = new Size(200, 50);
            lblTotalValue.Font = new Font("Segoe UI", 28F, FontStyle.Bold);
            lblTotalValue.ForeColor = Color.FromArgb(34, 197, 94);
            lblTodaySalesLabel.Text = "📈 Today's Sales";
            lblTodaySalesLabel.Location = new Point(680, 20);
            lblTodaySalesLabel.Size = new Size(200, 30);
            lblTodaySalesLabel.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            lblTodaySalesLabel.ForeColor = Color.FromArgb(148, 163, 184);
            lblTodaySales.Text = "$0.00";
            lblTodaySales.Location = new Point(680, 50);
            lblTodaySales.Size = new Size(200, 50);
            lblTodaySales.Font = new Font("Segoe UI", 28F, FontStyle.Bold);
            lblTodaySales.ForeColor = Color.FromArgb(168, 85, 247);
            // Low Stock Table
            lblLowStockTitle.Text = "⚠️ Low Stock Alerts";
            lblLowStockTitle.Location = new Point(20, 120);
            lblLowStockTitle.Size = new Size(400, 30);
            lblLowStockTitle.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            lblLowStockTitle.ForeColor = Color.White;
            dgvLowStock.Location = new Point(20, 150);
            dgvLowStock.Size = new Size(600, 200);
            dgvLowStock.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvLowStock.ReadOnly = true;
            dgvLowStock.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvLowStock.BackgroundColor = Color.FromArgb(30, 41, 59);
            dgvLowStock.BorderStyle = BorderStyle.None;
            dgvLowStock.GridColor = Color.FromArgb(51, 65, 85);
            dgvLowStock.Font = new Font("Segoe UI", 10F);
            dgvLowStock.ForeColor = Color.White;
            dgvLowStock.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(51, 65, 85);
            dgvLowStock.ColumnHeadersDefaultCellStyle.ForeColor = Color.White;
            dgvLowStock.ColumnHeadersDefaultCellStyle.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            dgvLowStock.RowsDefaultCellStyle.BackColor = Color.FromArgb(30, 41, 59);
            dgvLowStock.RowsDefaultCellStyle.ForeColor = Color.White;
            dgvLowStock.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(51, 65, 85);
            dgvLowStock.AlternatingRowsDefaultCellStyle.ForeColor = Color.White;
            // Recent Transactions Table
            lblRecentTransactionsTitle.Text = "📊 Recent Stock Transactions";
            lblRecentTransactionsTitle.Location = new Point(640, 120);
            lblRecentTransactionsTitle.Size = new Size(400, 30);
            lblRecentTransactionsTitle.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            lblRecentTransactionsTitle.ForeColor = Color.White;
            dgvRecentTransactions.Location = new Point(640, 150);
            dgvRecentTransactions.Size = new Size(600, 200);
            dgvRecentTransactions.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvRecentTransactions.ReadOnly = true;
            dgvRecentTransactions.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvRecentTransactions.BackgroundColor = Color.FromArgb(30, 41, 59);
            dgvRecentTransactions.BorderStyle = BorderStyle.None;
            dgvRecentTransactions.GridColor = Color.FromArgb(51, 65, 85);
            dgvRecentTransactions.Font = new Font("Segoe UI", 10F);
            dgvRecentTransactions.ForeColor = Color.White;
            dgvRecentTransactions.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(51, 65, 85);
            dgvRecentTransactions.ColumnHeadersDefaultCellStyle.ForeColor = Color.White;
            dgvRecentTransactions.ColumnHeadersDefaultCellStyle.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            dgvRecentTransactions.RowsDefaultCellStyle.BackColor = Color.FromArgb(30, 41, 59);
            dgvRecentTransactions.RowsDefaultCellStyle.ForeColor = Color.White;
            dgvRecentTransactions.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(51, 65, 85);
            dgvRecentTransactions.AlternatingRowsDefaultCellStyle.ForeColor = Color.White;
            // Add controls to form
            Controls.Add(panelContextDrawer);
            Controls.Add(panelMainContent);
            Controls.Add(panelSidebar);
            Controls.Add(panelTopBar);
            // Initially show dashboard
            panelDataTable.Controls.Add(panelDashboard);
            panelTopBar.ResumeLayout(false);
            panelSidebar.ResumeLayout(false);
            panelMainContent.ResumeLayout(false);
            panelContentHeader.ResumeLayout(false);
            panelDataTable.ResumeLayout(false);
            panelContextDrawer.ResumeLayout(false);
            panelDrawerContent.ResumeLayout(false);
            panelDashboard.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)dgvMainData).EndInit();
            ((System.ComponentModel.ISupportInitialize)dgvLowStock).EndInit();
            ((System.ComponentModel.ISupportInitialize)dgvRecentTransactions).EndInit();
            ResumeLayout(false);
        }
    }
}